### PR TITLE
ran npm install

### PR DESCRIPTION
**Pull request by micmania1**

### CODE REVIEW

**Comment by ss23** [comment]
Shouldn't this be handled like composer?

**Comment by hafriedlander** [comment]
@ss23 It is - package.json defines the dependancies. This is the complied css after updating the dependancies to the latest (basically, fontawesome 4.3 => 4.4)

**Comment by ss23** [comment]
What I meant was, why would we package the results of a npm install? Shouldn't we *not* package it, like we don't package the results of a composer install?

**Comment by hafriedlander** [comment]
We aren't. This is the _compiled_ outcome. npm install puts everything under the node_modules folder (which hasn't been committed).

**Comment by hafriedlander** [comment]
(However it's probably going to need to be re-done once all the other PRs are merged. Checking in complied css == merge headaches)

**Comment by micmania1** [comment]
Paul made the same change and its been merged.

**Pull request closed without merging**
