### PR TITLE
Fixing a regression from 29f1929835 where file hash isn't created.

### PR DESCRIPTION
**Pull request by halkyon**

### CODE REVIEW

**Comment by halkyon** [comment]
This raises another question though: hashing a large snapshot can take a while and be an expensive operation. Is it worth doing such a thing?

**Comment by stojg** [comment]
Are we using the ArchiveFileHash for anything?

**Comment by halkyon** [comment]
@stojg I don't know, couldn't find any references. Anyone else know?

**Comment by stojg** [comment]
it’s an regression, so from not working to working as bad as before.. is better.. I’ll merge

**Pull request merged**
