### PR TITLE
Long lines and tailing spaces

### PR DESCRIPTION
**Pull request by spekulatius**
adjusting some long lines into short onces and remove some tailing spaces

### CODE REVIEW

**Comment by micmania1** [comment]
Hey, master has changed quite a bit since this commit. Can you please rebase? Could also do the same for #228?

Thanks.

**Comment by spekulatius** [comment]
Hello @micmania1 ,

thanks for looking at this. I rebased this. Can you merge this?

Cheers

**Comment by halkyon** [comment]
@spekulatius Sorry, I had to partially revert (see 9ff5bac). The template changes conflicted with the recent changes we've been doing in master.

**Comment by spekulatius** [comment]
all good @halkyon 

I can just open a new pull request later on.

**Pull request merged**
