### PR TITLE
Make all the things responsive

### PR DESCRIPTION
**Pull request by clarkepaul**
This covers most of the layout to make it usable on smaller devices. This work will require changes to the root repo and a fix to the security page which isn't getting the javascript (should be merged already - not tested)

### CODE REVIEW

**Comment by clarkepaul** [comment]
needs merge here as well https://code.platform.silverstripe.com/silverstripe/deploy-silverstripe-com/merge_requests/30

**Comment by micmania1** [comment]
This doesn't merge cleanly. Can you rebase and then push your changes again?

**Comment by clarkepaul** [comment]
@micmania1 done the rebase finally

**Comment by stojg** [comment]
Tested locally, there are a couple of quirks in small screen mode, but it's actually responsive so the in general it's a huge improvement.

**Pull request merged**
