### PR TITLE
Added a warning about signed commit issues

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by madmatt** [comment]
This will only work if pipelining is enabled. You'll also have to change `DeployForm` to include the message I believe for environments that don't have pipelines enabled or configured.

Note: It's been years since I've touched Deploynaut code, I could well be wrong :)

**Comment by assertchris** [comment]
Could someone else confirm this? I have no idea of how Deploynaut is structured - this was the only template change I could infer from the URL I use to deploy...

@hafriedlander @halkyon @stojg @mateusz

**Comment by stojg** [comment]
Looks like one possible solution for the older version of deploynaut. But I would be keen to get an related issue. I saw @madmatt opened an issue in the gitlib package at https://github.com/gitonomy/gitlib/issues/108

**Comment by madmatt** [comment]
Yeah, I was thinking that gitlib was some kind of PHP extension, but it's actually just a PHP script shelling out to `git`, so it's much easier for us to just fix ourselves :)

**Comment by halkyon** [comment]
This looks like it can be closed, as the issue was fixed upstream in gitonomy. @stojg Can you confirm?

**Comment by stojg** [comment]
I'm closing it, it's fixed as far as I can tell. If not, feel free to reopen.

**Pull request closed without merging**
