### PR TITLE
Add a quick summary of the deployment next to the deploy button.

### PR DESCRIPTION
**Pull request by mateusz**

### CODE REVIEW

**Comment by mateusz** [comment]
screen shot 2015-09-10 at 9 51 07 am

**Comment by halkyon** [comment]
How much do we care about hardcoding platform-specific URLs etc? Also, does this work for Capistrano still, or just not used at all?

**Comment by mateusz** [comment]
Capistrano screenshot:
screen shot 2015-09-10 at 9 52 41 am

**Comment by clarkepaul** [comment]
Nice work with the styling @mateusz :+1: 
On the last screen it Still says "Code deployment" and "Full" on the side.

**Comment by mateusz** [comment]
screen shot 2015-09-10 at 10 10 57 am
screen shot 2015-09-10 at 10 12 26 am

**Comment by clarkepaul** [comment]
Beaut!

**Comment by mateusz** [comment]
@clarkepaul wait till you see the gimmick :P

**Pull request merged**
